/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atguigu_guolu_JNI */

#ifndef _Included_com_atguigu_guolu_JNI
#define _Included_com_atguigu_guolu_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atguigu_guolu_JNI
 * Method:    getPressure
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atguigu_guolu_JNI_getPressure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
