/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atguigu_jniproject_JNI */

#ifndef _Included_com_atguigu_jniproject_JNI
#define _Included_com_atguigu_jniproject_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atguigu_jniproject_JNI
 * Method:    helloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atguigu_jniproject_JNI_helloJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
